# Generated by Django 2.2.8 on 2019-12-28 17:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20191225_0350'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackUserPageVists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.CharField(max_length=64)),
                ('page', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=400)),
                ('last_visited', models.DateTimeField(default=django.utils.timezone.now)),
                ('number_visits', models.PositiveIntegerField(default=0)),
                ('is_service', models.BooleanField(default=True)),
            ],
        ),
    ]
