# Generated by Django 2.2.8 on 2019-12-30 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_trackuserpagevists'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrackUserPageVists',
        ),
    ]
