# Generated by Django 2.2.8 on 2020-01-02 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_delete_trackuserpagevists'),
        ('service', '0004_auto_20200102_1353'),
    ]

    operations = [
    ]
