# Generated by Django 2.2.8 on 2020-01-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_merge_20200102_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedFileInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.CharField(max_length=64)),
                ('file_name', models.CharField(max_length=300, null=True)),
                ('message_hash', models.CharField(max_length=300)),
                ('signature', models.CharField(max_length=300)),
                ('file_hash', models.CharField(max_length=300)),
            ],
        ),
    ]
